### ISSUE TITLE
The engine code and its consistency with the original nim code

### ISSUE THREAD

**Issue by wanhesong** [ronaldosvieira/gym-locm#6]
Hi, thanks for the great repo which makes life easier for those who want to do the RL training:-) Also, the code structure looks neat and it's easy to single out the desired modules for one's own project (thanks for providing the MIT license:-) )! 

I'm trying to figure out how the `env.step(...)` implements. To my understanding, it seems that you "reproduce" the whole engine code of "[the original nim one](https://github.com/acatai/Strategy-Card-Game-AI-Competition/blob/master/referee-nim/Engine/State.nim#L9)". In particular, the [Python code here ](https://github.com/ronaldosvieira/gym-locm/blob/master/gym_locm/engine.py#L511) receives the input actions (performed by the agents) and modify the `State` instance accordingly. If this were true, how should we ensure the behaviors (i.e., the (state, action) -> new_state transition) are consistent with the original nim code? (Maybe the only way is to read and compare the nim code and Python code? Also, when locm 1.5 comes out we may need another `engine.py` as the `State` and `Action` can be totally different?)

**Comment by ronaldosvieira** [comment]
Hi @wanhesong!

Yes, gym-locm doesn't use the Java or the Nim implementation of LOCM provided by [acatai/Strategy-Card-Game-AI-Competition](https://github.com/acatai/Strategy-Card-Game-AI-Competition) but instead reimplements the game from scratch using Python (as you found on engine.py). It has no relation to those implementations, so I can't guarantee that it is 100% consistent. 

However, last year, to check consistency, I performed the following experiment: 
Using deterministic agents (Coac and Baseline2 from the SCGAI competition), I ran 4.000 matches on [LOCM's original Java implementation](https://github.com/acatai/Strategy-Card-Game-AI-Competition/tree/master/referee-java) and collected all state and action outputs. Then, I recreated all of those matches' initial states (including the hidden information) on gym-locm's engine and executed them using the same agents to check whether the (state, action) -> new_state transitions of the whole matches would be identical. They were not, but after a handful of fixes, all 4.000 matches became identical on both engines.

I've made many changes in the repository since then, so I guess it's a good time to redo this experiment. Thanks for reminding me. :)

Also, about LOCM 1.5: I'd prefer to use the same State and Action classes for version 1.5 while keeping retrocompatibility with version 1.2 (so that one could instantiate State as a LOCM 1.2 or a LOCM 1.5 game by passing a different parameter). But whether that will be viable depends on how different version 1.5 will be.

**Comment by wanhesong** [comment]
Hi @ronaldosvieira , what an effort! And thanks for providing the technical details. Just a few more questions:

* can we say the current `gym-locm` engine code (e.g., commit 582dab on 2022-02-17) has passed the consistency checking as you mentioned above so that the state, action -> new_state transition is supposed to be the same with the Java referee code used in last year competition?
* do you have the plan to release the code for consistency checking?

And really looking forward to your Python code on locm 1.5 :-)

**Comment by wanhesong** [comment]
I see, there were further changes since your previous consistency checking. Any schedule for dosing this? Or maybe you could push a commit for the code of consistency checking so that any `gym-locm` user is able to do it anytime (Or maybe Travis-CI?).

**Comment by ronaldosvieira** [comment]
- No - the current commit has not been tested for consistency.
- Yes - I plan to redo this consistency check again in the following weeks. Unfortunately, I seem to have lost its source code, so I'll have to implement it again. I will definitely add this code to the repo this time. Setting up Travis to perform this check automatically is a great idea, and I look forward to it.

FYI: in the `feature/constructed` branch there is a preliminary implementation of what I think the new deck-building mode in LOCM 1.5 will be.

**Comment by wanhesong** [comment]
It's awesome! Thanks :-)
