### ISSUE TITLE
Coac Agent Implementation

### ISSUE THREAD

**Issue by wanhesong** [ronaldosvieira/gym-locm#9]
Hi, I guess this line
https://github.com/ronaldosvieira/gym-locm/blob/582dab87b6b1a8a579818cc7484af219b442202a/gym_locm/agents.py#L366

should be something like `if len(state.available_actions) == 0:`, compared to the original Coac C++ code here:
https://github.com/acatai/Strategy-Card-Game-AI-Competition/blob/master/contest-2020-08-COG/Coac/main.cpp#L1070

Or did I misunderstand the code?

**Comment by ronaldosvieira** [comment]
Hi @wanhesong!

Thanks for pointing it out. The behavior of `state.available_actions` has changed since the Coac agent was implemented (now the PASS action is always on the list), so line 366 does not work anymore. I believe a correct check would be `len(legal_moves) == 1 and legal_moves[0].type == ActionType.PASS`.

FYI: Coac's implementation on gym-locm is outdated and does not live up to the original implementation (Python is way slower than C++ and the performance of tree search algorithms is very sensitive to the amount of time available). If you wish to use Coac as an agent in gym-locm, I recommend you check the NativeAgent class (and maybe the NativeDraftAgent and NativeBattleAgent), which enables you to use agents from the SCGAI competition. :)

**Comment by wanhesong** [comment]
Hi @ronaldosvieira, thanks for the reply :-) Yes, I further read the `gym-locm` code and compared it to the original Coac code. I've done exactly the same modification you just mentioned. 

Besides, I also set `self.time_limit_ms` be large enough (e.g., 3000ms) and modify the `def _brute_force_leaf` implementation slightly (the sign of the returned score). After all these modifications, the `CoacBattleAgent` now seems to work well and defeats the other `MaxAttackBattleAgent`, `GreedyBattleAgent`, `RuleBasedBattleAgent` in a reasonable win-rate. However, I'm still not sure whether the depth-one enemy search makes sense in that whether the enemy can see my hand cards during his search. Another minor difference is that the original Coac works for the whole turn (several steps), while the gym-locm CoacBattleAgent works for one step.

And thanks for mentioning the `NativeAgent`, didn't notice it until reading your reply. Seems like a nice tool. Would appreciate if you could provide some examples, say, how to call the original Coac Agent using the NativeAgent/NativeDraftAgent/NativeBattleAgent?

**Comment by ronaldosvieira** [comment]
> After all these modifications, the `CoacBattleAgent` now seems to work well and defeats the other `MaxAttackBattleAgent`, `GreedyBattleAgent`, `RuleBasedBattleAgent` in a reasonable win-rate.

Great news!

> However, I'm still not sure whether the depth-one enemy search makes sense in that whether the enemy can see my hand cards during his search.

As far as I remember, the gym-locm implementation of Coac "cheats" since it knows which SUMMON and USE actions the opponent can make. That may be solved by considering only ATTACK actions for the opponent during the search.

> Another minor difference is that the original Coac works for the whole turn (several steps), while the gym-locm CoacBattleAgent works for one step.

Yeah, the Agent interface in gym-locm requires agents that act step by step. A more efficient Coac implementation would let it calculate all actions of a turn as in the original Coac but return just the first one and keep the rest in a "buffer". So the next calls to agent.act(state) would pop a buffered action instead of performing the search again (`NativeAgent` does this).

> Would appreciate if you could provide some examples, say, how to call the original Coac Agent using the NativeAgent/NativeDraftAgent/NativeBattleAgent?

Sure.

```python
from gym_locm.agents import NativeAgent

# agent = NativeAgent("python3 /path/to/Baseline2/main.py", stateful=False, verbose=False)
agent = NativeAgent("./path/to/coac", stateful=True, verbose=False)
```

The first parameter is a string containing how you would execute the agent in a terminal (e.g., for Coac that may be `./path/to/coac` while for Baseline2 that may be `python3 /path/to/Baseline2/main.py`). The stateful parameter means whether the agent is stateful (can we play multiple matches with the same instance of the agent? Or should we create a new instance for every match?). The verbose parameter just prints additional stuff - useful for debugging.

`NativeDraftAgent` and `NativeBattleAgent` are variations for cases where you just need the agent to play a single phase of the game (respectively, the draft or the battle).

**Comment by wanhesong** [comment]
That is wonderful! Thanks so much for providing the example, will try it out :-)
